# Generated by Django 2.2.16 on 2022-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='aaa', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('UR', 'user'), ('MD', 'moderator'), ('AD', 'admin')], default='UR', max_length=2, verbose_name='Роль пользователя'),
        ),
    ]
