# Generated by Django 2.2.16 on 2022-05-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220511_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
