# Generated by Django 2.2.19 on 2022-05-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220513_1050'),
        ('reviews', '0003_auto_20220513_1827'),
    ]

    operations = [
    ]
